name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: arc-runner-set
    permissions:
      contents: write # Required to push tags

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history and existing tags

      - name: Extract Version from Gradle
        id: gradle_version
        run: |
          # Extract version from build.gradle: version = '1.0.0'
          VERSION=$(grep "^version = " build.gradle | awk -F"'" '{print $2}')
          echo "Base Gradle Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and Push Tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ steps.gradle_version.outputs.version }}

